### ISSUE TITLE
Do not lowercasing request headers

### ISSUE THREAD

**Issue by rohmanhm** [sindresorhus/ky#105]
Here's my code extend `ky` instance.

```ts
  ky.extend({
    prefixUrl: API_BASE_URL,
    headers: {
      Authorization: `Bearer ${token}`
    }
  })
```

Here's what i've got on network tab request header.
![image](https://user-images.githubusercontent.com/7524911/53864068-2fffca80-401e-11e9-9493-af585c4c13ca.png)

Why did you lowercasing my header key?

**Comment by sindresorhus** [comment]
HTTP headers are case insensitive.

**Comment by rohmanhm** [comment]
Yeah but just let the user choose how they're gonna write their headers.
Don't force them to use lowercased headers.

IMHO

**Comment by szmarczak** [comment]
> Yeah but just let the user choose how they're gonna write their headers.

Is there any reason why? According to the spec it doesn't matter.

**Comment by sholladay** [comment]
I mostly agree with you in principle @rohmanhm. But doing this would actually add some complexity to Ky and I don't think it's worth it given what the spec says.

The reason for the added complexity is that Ky itself is not explicitly lowercasing headers. It's merely a side effect of using [`new Headers()`](https://developer.mozilla.org/en-US/docs/Web/API/Headers/Headers). Since that's a browser API that we don't control, we'd have to avoid using it to achieve your desired result. I tried removing our usage of `Headers` in PR #74 (for different reasons) but we ended up keeping it because it turned out to be [kind of messy](https://github.com/sindresorhus/ky/pull/74/commits/10a1383bcef94efdd81f1ffc8fb374463b5316f3). Also see the discussion here:
 - https://github.com/sindresorhus/ky/pull/74#discussion_r245502333
 - https://github.com/sindresorhus/ky/pull/74#discussion_r245523162

That implementation could be made much simpler if we were willing to drop support for a `Headers` instance in our `headers` option, but I'm not sure that is the right approach. So unless you can come up with something simpler, I doubt we're going to do this.

**Comment by felixdenoix** [comment]
Hi,
I stumbled upon this issue while trying to retrieve the same `Authorization` header from a request response and it took me a few minutes to realize that even though the headers are case insensitive, the response headers getter is not 😞:
```
response.headers.get('Authorization') // returns null
response.headers.get('authorization') // returns the correct value
```
Do you think an indication could be added in the `readme` on the fact that **Ky** lowercases all headers and that retrieving them requires the use of their lowercase name ? (I could create the pr if you like)
(also sorry for digging up a closed issue)

**Comment by sholladay** [comment]
@felixdenoix I'm not against a documentation PR related to this, but it really has nothing to do with Ky. It's because you are using [Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers) and that's how it behaves. It would be more useful, IMO, to contribute to improving the MDN documentation rather than Ky, and then we can link to it.

**Comment by i-CNNN** [comment]
> HTTP headers are case insensitive.

HTTP不区分大小写，但是后台接口区分大小写，这种情况，总不能要求后台修改请求头全部为小写吧？或者加一个选项，可以自由控制大小写的转换？
