### ISSUE TITLE
No way to access response body on non-2XX responses

### ISSUE THREAD

**Issue by davalapar** [sindresorhus/ky#107]
```js
    try {
      const result = await ky.post('/somepaththaterrors', {
        json: {
          // orsomeparametersthaterrors
        },
      }).json();
    } catch (error) {
      alert(error.message); // Bad Request
    }
```

If on express we do `res.status(400).send('Some error here');`, ky's `error.message` will be "Bad Request" and not "Some error here".

Chrome's Console Network -> XHR requests tab will show that the request returned a response body containing "Some error here" but if we try to traverse the `error` object, there is no path or property that leads us to the returned response body "Some error here"

Is this the intended outcome? I was just thinking that the body of a 4XX response could let us relay additional information on what makes the request a Bad Request.

**Comment by sholladay** [comment]
We do provide the response. See the documentation on our [`HTTPError`](https://github.com/sindresorhus/ky/tree/8c6abab989367abf756efd8b4faa549e7dfe0a54#kyhttperror) class.

You can access the response as `error.response`.

**Comment by davalapar** [comment]
Hi @sholladay, thanks for responding.

I've seen the `response` object is accessible within the error, but the body is just a ReadableStream? (images provided)

It also has `.text()` and `.json()` methods but they only return a DOMException. 

```js
// express
  app.post('/path-that-returns-400-with-response-body', async (req, res) => {
      res.status(400).send('Some error here');
  });
```

```js
// client
    try {
      await ky.post('/path-that-returns-400-with-response-body', {
        json: {
          // anything
        },
      });
    } catch (error) {
      console.log({ error });
    }
```

<img src="https://i.imgur.com/t3o6n9L.png" />
<img src="https://i.imgur.com/77HTexO.png" />
<img src="https://i.imgur.com/QGMlRCC.png" />

**Comment by mesqueeb** [comment]
@sholladay I am also trying to access `error.response` to see the body on non 2xx responses.

Do you have a complete example of how I can do this? Maybe it could also be added to the Readme for people (like me) who are less experienced with http api's.

**Comment by mesqueeb** [comment]
@sholladay I have the same problem where I try to access the response body by `error.response` but it just says `ReadableStream`.

Can you share your solution please?

**Comment by sholladay** [comment]
Sure, I'll walk you through it.

> ky.HTTPError

This is referencing the _class_ `HTTPError`, which is something that Ky defines and exports so that you can more easily identify HTTP errors when they happen, by checking whether a given error is an instance of `HTTPError`.

> Exposed for instanceof checks.

This is what I was talking about above. Basically, the class is useful because you can write `if (error instanceof ky.HTTPError) {` in your code to check if an error is specifically an HTTP error, as opposed to, say, a network error.

> The error has a response property with the Response object.

Here, "the error" is any instance of `HTTPError`. So it's saying that all HTTP errors thrown by Ky will have a property named `response` that is an instance of the [`Response`](https://developer.mozilla.org/en-US/docs/Web/API/Response) class. See MDN for details about what a `Response` instance is like and how to use it. In short, it is a stream (as you mentioned), which represents some data that Ky has received from a server. Inside of the response is a status code, headers, and maybe a body.

There are a number of different ways to read the value of the response body, which is likely what you want to do. Specifically, you can use any of the methods from the [`Body`](https://developer.mozilla.org/en-US/docs/Web/API/Body) class, because `Response` implements the `Body` methods as well as some of its own.

Let's say that your server responds with a 404 and a simple text message saying "Sorry, page not found." You could read that message from the response like this...

```
try {
    await ky.get('/nonexistent);
}
catch (error) {
    const serverMessage = await error.response.text();
    console.log('Server error: ' + serverMessage);
}
```

**Comment by ShivamJoker** [comment]
If you want it as an object make sure to use `.json()` instead of `text`

**Comment by georgejdli** [comment]
Is there a way to do the error processing with the afterResponse hook so I don't need to call .json() everywhere I handle errors?

**Comment by sholladay** [comment]
@georgejdli yes you can. Here is a snippet from one of my production apps:

```js
const api = ky.extend({
    credentials : 'same-origin',
    mode        : 'same-origin',
    prefixUrl   : '/api/',
    timeout     : 30000,
    hooks       : {
        afterResponse : [
            async (request, options, response) => {
                if (response.status === 401) {
                    location.assign('/login?next=' + encodeURIComponent(location.pathname));
                }
                else if (!response.ok) {
                    response.payload = await response.json();
                    return response;
                }
            }
        ]
    }
});
```

Note that it is important to `return response` if you've made any modifications to the response that you want to take effect, as in the code above. Ky passes a _cloned_ response to hooks, but uses the original non-cloned response internally unless you return a response object.

**Comment by olsonpm** [comment]
for future googlers - v2 now pre-parses the error response, so you access the response body via `error.data` instead of awaiting `error.response.text()`

---

relevant v2 change log

> Add [data](https://github.com/sindresorhus/ky#httperror) property to HTTPError with pre-parsed response body (https://github.com/sindresorhus/ky/pull/823) https://github.com/sindresorhus/ky/commit/1341f5ca56c96c9440e6e8d0d624c871bb1b7929
> 
> The response body is automatically consumed and parsed, fixing resource leaks and making error details immediately available without awaiting (https://github.com/sindresorhus/ky/issues/642).
