### ISSUE TITLE
Expected a Promise rejection for option errors

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/ky#131]
#### Expected behavior

A Promise rejection.

#### Current behavior

Errors are thrown directly.

#### Code to reproduce

```js
ky('/', {
	prefixUrl: 'https://example.com/'
});
```

**Comment by sindresorhus** [comment]
The existing behavior is correct. `ky()` doesn't return a `Promise`.

**Comment by szmarczak** [comment]
It does: it returns `fetch()`, which returns a Promise which resolves with a Body.

**Comment by sholladay** [comment]
I see only downsides to returning validation errors as rejections (including but not limited to the fact that some environments swallow unhandled rejections by default). I can't think of any practical reason to do so. That's just my two cents.

**Comment by szmarczak** [comment]
What are the downsides? I don't see any :confused:

**Comment by sholladay** [comment]
Benefits of throwing synchronously for input validation:
 - Shorter syntax for us
 - It is technically a bit faster (no waiting for the [microtask queue](https://jsblog.insiderattack.net/promises-next-ticks-and-immediates-nodejs-event-loop-part-3-9226cbe7a6aa))
 - By distinguishing these from operational errors, it becomes harder for the user to ignore or not notice them (important to me because these are fatal programmer errors).
 - Causes the program to _actually_ crash, as expected. Avoids the problem of some environments sending promise rejections into the abyss. (See [here](http://jamesknelson.com/are-es6-promises-swallowing-your-errors/) and [here](https://github.com/nodejs/node/issues/20392), among others.)

I'm not trying to say it's a huge deal. But to me, throwing synchronously seems obviously superior.

The best counter argument I can come up with is that rejecting instead of throwing gives us some squishy notion of consistency that might be nice for users who _do_ want to ignore these errors for some reason. But I can't imagine a scenario when someone would want to ignore input validation errors - it would effectively just make Ky a no-op, so there's no point.

**Comment by szmarczak** [comment]
> Shorter syntax for us

I'm rebasing the code (you can see the PR). The shorter one is Promise rejection.

> It is technically a bit faster 

That's true.

> By distinguishing these from operational errors, it becomes harder for the user to ignore or not notice them
> Causes the program to actually crash, as expected.

It depends on your point of view. Unhandled rejections? No problem, use global catch.

@sindresorhus https://github.com/sindresorhus/ky/pull/127#discussion_r277155396 said:

> The Promise spec says that Promise-returning functions should always reject, and never synchronously throw.

So, replying to:

> The existing behavior is correct. ky() doesn't return a Promise.

I disagree. `ky()` **does** return a Promise. It's generated by `fetch()` and resolves with a `Body`.

**Comment by sindresorhus** [comment]
Sorry, @szmarczak is correct. I was reading the docs:

> Returns a Response object with Body methods added for convenience.

Which is incorrect. It should say:

> Returns a Promise for a Response object with Body methods added for convenience.

**Comment by sindresorhus** [comment]
@sholladay This should always be followed:

> The Promise spec says that Promise-returning functions should always reject, and never synchronously throw.

I was only closing as I was fooled by the docs.

**Comment by sholladay** [comment]
I haven't been able to find anything like that in ECMA-262, nor in Promises/A+. I might have missed it, but I'm skeptical they would make that choice as part of the spec.

**Comment by sindresorhus** [comment]
https://www.w3.org/2001/tag/doc/promises-guide#always-return-promises

**Comment by sholladay** [comment]
FWIW, that is not a spec. And this is the only part that I disagree with:
> Even argument validation errors are not OK.

Anyway, I had to make [throw-rejects](https://github.com/sholladay/throw-rejects) as a more general solution to get async programs to crash properly and it will handle this case for anyone who remembers to use it. I can live with it...

**Comment by sindresorhus** [comment]
> Anyway, I had to make throw-rejects as a more general solution to get async programs to crash properly and it will handle this case for anyone who remembers to use it. I can live with it...

Hehe. I have https://github.com/sindresorhus/hard-rejection I think the Node.js team plans to eventually make uncaught rejections a hard error.

**Comment by sholladay** [comment]
Closing since this should be done, ever since the re-write to `async`/`await`.
