### ISSUE TITLE
Document how to override headers in beforeRequest hook

### ISSUE THREAD

**Issue by kraniebrud** [sindresorhus/ky#139]
Hi, 
thanks for a fantastic lib !
I am trying to modify headers with the `beforeRequest` in `hooks`, but I can't make it work.

I am having the following code

```js
import ky from 'ky-universal'

const prefixUrl = 'https://jsonplaceholder.typicode.com'

const beforeRequestFns = [
  (options) => {
    console.log(options.headers)
    options.headers.unicorn = 'rainbow'
  }
]

const options = {
  prefixUrl,
  hooks: {
    beforeRequest: beforeRequestFns,
  },
}

const client = ky.create({ ...options })

client.extend({ headers: { foo: 'bar' } }).get('todos/1')

export default client

```
From the `Network` tab in Chrome I don't see my 'unicorn' in the request headers, I see the 'foo' is there alright :)

What I am trying to achieve is that every request towards the defined `prefixUrl` is supposed to be able add authentication to the headers do to some conditions.

From what I can tell from the readme this should be possible, so I am guessing that I am just doing it wrong ? 

Can you help? :) -- thanks

**Comment by sholladay** [comment]
Yes, this is possible to do, it's just not entirely obvious at the moment.

Ky [normalizes the headers](https://github.com/sindresorhus/ky/blob/2ded27572ec491e6c9e594ebcd2f94cc8c3957db/index.js#L205) internally to be a [Headers](https://developer.mozilla.org/en-US/docs/Web/API/Headers) instance, so that we can deal with them in a consistent way.

This is briefly mentioned in [`beforeRequest` documentation](https://github.com/sindresorhus/ky#hooksbeforerequest):
> The hook function receives the normalized options as the first argument.

At the moment, we don't have much documentation related to the normalization process. But in this case, the solution is simply to set the header using the appropriate methods of the `Headers` class, as assigning a property to the instance won't do anything.

```js
hooks: {
    beforeRequest : [
        (options) => {
            options.headers.set('unicorn', 'rainbow');
        }
    ]
}
```

Since we already mention overriding headers in the documentation, it would be good to add this as a working example. PRs welcome!

**Comment by kraniebrud** [comment]
Wauv so close 🤦‍♂ , thanks for the reply ! I will try it out when I find the time to refactor my current code at some point.

**Comment by joaovieira** [comment]
The `BeforeRequestHook` type is incorrect too (https://github.com/sindresorhus/ky/blob/master/index.d.ts#L5) as it doesn't receive neither `Options` nor `RequestInit` but a new type with merged options from both, plus the new `headers`.

Will open a PR to fix that.

**Comment by Yesky0** [comment]
Why "normalized" word disappeared from docs? Is there cases when headers could be in another form?

**Comment by sholladay** [comment]
No, we always normalize them to a `Headers` instance.

https://developer.mozilla.org/en-US/docs/Web/API/Headers
