### ISSUE TITLE
Don't throw on 3xx with blob

### ISSUE THREAD

**Issue by Farkal** [sindresorhus/ky#144]
When I query an url returning 304  this code doesn't throw: 
```js
try {
      return ky.get(url, {
        headers,
        stream: true,
        timeout: false
      })
      .blob()
    } catch (e) {
      throw e
    }
```
Is there any way to get the http status code and throw ?

**Comment by sindresorhus** [comment]
See this related discussion: https://github.com/sindresorhus/got/issues/251 The consensus there were to not throw and instead document the case and return an empty value.

What does the above snippet return?

**Comment by sholladay** [comment]
In terms of the current behavior, it should definitely be rejecting the promise due to [this line](https://github.com/sindresorhus/ky/blob/2ded27572ec491e6c9e594ebcd2f94cc8c3957db/index.js#L235-L237), since `reponse.ok` is only `true` for 2xx status codes.

I do see that while you wrapped `ky.get()` in a `try {}`, you didn't actually `await ky.get()`. So wherever you're returning the promise to will have to handle the error case, as your `catch` block in your example code will not be receiving the `HTTPError` (it would, however, catch any synchronously thrown errors from the constructor).

**Comment by Farkal** [comment]
The snippet return a blob containing the html page.
It doesn't change anything if I await inside my function. The problem is with blob(). If I do the same request with json() it throw. So I think blob doesn't catch http errors properly.

**Comment by sholladay** [comment]
I looked pretty carefully and could not find any basis for a theory about the behavior you are describing, so I went and made a CodeSandBox for it. Alas, I cannot reproduce this. Could you try it? Just click the button and check the console below the CodeSandBox browser window. If you make edits to the code, don't forget to restart the server, as there is no watch mode configured at the moment.

https://codesandbox.io/embed/sad-star-in3f3

**Comment by Farkal** [comment]
Yeah excuse me you where right it's my browser that after the first 200 return 304.
But the first 200 is the result of a redirection (silently followed) so is there a way to tell ky not to follow redirection ?

**Comment by sholladay** [comment]
It sounds like you are asking for a way to throw an error when a redirect is received. Are you sure that's what you want? If so, I'd be curious to hear why.

Anyway, this should work:
https://developer.mozilla.org/en-US/docs/Web/API/Response/redirected#Disallowing_redirects

```js
await ky.get(url, { redirect : 'error' });
```
