### ISSUE TITLE
`afterResponse` hook doesn't work with the new expanded `retry` option

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ky#167]
Introduced by https://github.com/sindresorhus/ky/commit/d4ddb7ab4ec0d5baff73b3c038be48717592384d.

This test now fails: https://github.com/sindresorhus/ky/blob/a50948adeff0c2255626ed28465e126e095a7c04/test/hooks.js#L249

```
 hooks › `afterResponse` hook is called with input, normalized options, and response which can be used to retry

  /Users/sindresorhus/dev/oss/ky/index.js:3

   2:
   3: const getGlobal = property => {
   4:   /* istanbul ignore next */

  Rejected promise returned by test. Reason:

  Error {
    message: 'retry.methods must be an array',
  }

  normalizeRetryOptions (index.js:3:1536)
  new Ky (index.js:4:7)
  ky (index.js:8:1713)
  t.deepEqual.ky.post.hooks.afterResponse (test/hooks.js:275:15)
  fn (index.js:6:55)
```

// @whitecrownclown @lambdalisue

**Comment by whitecrownclown** [comment]
The issue here is that the `afterResponse` hook uses the already normalized options for `retry` and `methods` (`methods` is a `Set`). An error is thrown since they go through the same normalize process again inside this test when calling `ky`.

@sindresorhus
What do you think about not throwing [an error](https://github.com/sindresorhus/ky/pull/110#discussion_r317104937), but a promise rejection and also allow using both `Array` and `Set` as options?

**Comment by sholladay** [comment]
So, this may need a bit more brainstorming...

PR #180 fixed the failing test. It did so by filtering the options passed to hooks such that hooks only receive fetch/unknown options but no Ky options. In other words,`retry` and other Ky options are omitted from the `options` passed to hooks, so when the hook in that test gives its `options` back to Ky, no error is thrown, because `retry` is not there to be validated.

This works well enough and perhaps we should keep it that way. I've gone back and forth multiple times on whether I think hooks should receive Ky options. This issue, and the test being discussed here, made me think, "Yeah, hooks should receive Ky options." But when I went to go implement that with all Ky options included, I ran into a new problem: `json` and `body` are then both present and Ky throws an error because it considers those options to be mutually exclusive. This problem was never experienced before because prior to PR #180, some Ky options weren't given to hooks (including `json`), while others were. I'm not sure any intentional thought was put into it, the codebase just grew that way organically.

Some ways forward from here:
1. Include all Ky options in the `options` object, for consistency/clarity.
2. Include some Ky options in the `options` object, like how it used to be before PR #180. Perhaps exclude `json` in particular, since it can be parsed from `body` and Ky is stubborn about `body` and `json` not being allowed together.
3. Simply turn off the `body`/`json` exclusivity validation, just let `json` take precedence.
4. Include no Ky options, forcing hooks to use the same Ky instance to use the same configuration.

At the moment, I am leaning towards `3` or `4.
