### ISSUE TITLE
how to parse error response?

### ISSUE THREAD

**Issue by popuguytheparrot** [sindresorhus/ky#191]
I get error from my api. Error in json format. But i cant read it and got error 400 status
![image](https://user-images.githubusercontent.com/19804652/68027827-6d5b4b80-fcc4-11e9-879d-d415c3e16f33.png)

Error
![image](https://user-images.githubusercontent.com/19804652/68028101-0722f880-fcc5-11e9-80d9-8766225ebe1d.png)

Error response
![image](https://user-images.githubusercontent.com/19804652/68027894-9bd92680-fcc4-11e9-850c-5f1c58915714.png)

**Comment by sholladay** [comment]
The `error` object has a `response` property attached to it, which represents the HTTP response received from the server, if any. It's also possible for there to have been no response at all, such as when you are offline, in which case `error.response` will be `undefined`.

You can use the response the same way you would with `fetch`. For example, to get the error response body as JSON...

```js
const body = await error.response.json();
```

**Comment by popuguytheparrot** [comment]
@sholladay I cant use await. error.response.json().then(res => res) dont work

**Comment by sholladay** [comment]
Then your server probably didn't respond with valid JSON. I'm afraid that without more insight into your situation, I won't be able to help any further. "x doesn't work" does not tell me what is going wrong. I can't even copy your code to reproduce it, because you posted it as an image. All I can say is I use `error.response.json()` a lot in my apps. It should be working.

For help and support, I recommend posting a question to [Stack Overflow](https://stackoverflow.com). Feel free to link to the question here and I will happily look at it some more.

If you continue to think that there is a genuine bug in Ky, then please submit a pull request with a failing test case, or a bug report with more details, such as the Ky version and a reproducible code example, including the server code, if possible. I like to use codesandbox.io to host these things, especially if it includes a server, but that's up to you.
