### ISSUE TITLE
Error: The `content-type` header cannot be used with a FormData body. It will be set automatically.

### ISSUE THREAD

**Issue by alanshaw** [sindresorhus/ky#204]
In the browser:

```js
const req = new Request('http://google.com', { method: 'POST', body: new FormData() })
req.headers.has('content-type')
// true
```

It means we cannot pass this check even when no `content-type` header has explicitly been set.

https://github.com/sindresorhus/ky/blob/1a86d5bf16f9282e00cd35b149d2ec00826dbef7/index.js#L246-L248

So my call to ky is erroring in v0.16:

```js
    const res = await ky.post('dag/put', {
      timeout: options.timeout,
      signal: options.signal,
      headers: options.headers,
      searchParams,
      body: toFormData(serialized)
    }).json()
```

https://github.com/ipfs/js-ipfs-http-client/pull/1159

**Comment by sindresorhus** [comment]
// @sholladay

**Comment by sholladay** [comment]
Ah, interesting. Thanks for the good details and code examples, that is helpful.

Turns out we don't have any `FormData` tests besides [this one](https://github.com/sindresorhus/ky/blob/1a86d5bf16f9282e00cd35b149d2ec00826dbef7/test/main.js#L488-L495).

I'll be fixing this soon.

**Comment by sholladay** [comment]
I see two paths forward here:

1. Just remove the assertion. It's kind of opinionated without much benefit, anyway. We're actively preventing the user from doing something that they can do with `fetch`, which I have mixed feelings about. Though I've never needed to override the `content-type` of a `FormData` or `URLSearchParams` instance, maybe there is a use case for it. I wonder if this check has actually caught any real mistakes, as opposed to just slightly simplifying the user's code.

2. Check the provided options instead of the normalized request:
    ```js
    if (((supportsFormData && this._options.body instanceof globals.FormData) || this._options.body instanceof URLSearchParams) && (new Headers(this._options.headers)).has('content-type')) { 
    	throw new Error(`The \`content-type\` header cannot be used with a ${this._options.body.constructor.name} body. It will be set automatically.`); 
    }
    ```

**Comment by sindresorhus** [comment]
I would go with `1`. It's not really worth checking this. For example, what if the user sets the `content-type` in `.extend()` or a hook? Even if they set it to the same `content-type`, we would throw, so we would also have to check if it's different than expected. And there might be valid cases of needing to change the `content-type` of formdata.

**Comment by alanshaw** [comment]
Thanks for looking into this ❤️

**Comment by rangermeier** [comment]
I tried to prepare a PR for removing this assertion: https://github.com/rangermeier/ky/commit/82fe72b6e478f4296dcfdd4c149a1acba41254e1

 But it turns out, there's more broken with sending FormData. When issuing a POST request where `body` is FormData and setting some `searchParams`, the request doesn't contain the file.

I prepared  a codesandbox demonstrating this: https://codesandbox.io/s/ky-formdata-2uvcx

**Comment by rangermeier** [comment]
The PR now contains a fix for the issue concerning `searchParams`.
