### ISSUE TITLE
Issue with Retries after v0.16.0

### ISSUE THREAD

**Issue by zjr** [sindresorhus/ky#217]
This could very well be something I'm doing wrong or misunderstanding and if so I apologize.

Starting at v0.16.0 and continuing to v.0.16.1, there seems to be an issue with retries reusing a Request object (at least that's what the error tells me). Ky's fetch promise rejects with this:

```
TypeError: Failed to execute 'fetch' on 'Window': Cannot construct a Request with a Request object that has already been used.
    at Ky._fetch (index.js:395)
    at fn (index.js:257)
    at async Ky._retry (index.js:346)
    at async Promise.Ky.result.<computed> [as json] (index.js:299)
```

In v0.15.0 & below I would just get the error response from my API.

**Comment by sholladay** [comment]
Our [retry tests](https://github.com/sindresorhus/ky/blob/master/test/retry.js) are passing, although unfortunately I just noticed that many of the assertions are [not checking error messages](https://github.com/sindresorhus/ky/blob/d6ff489b62468b0fb3af3a23bfb4533888b20b57/test/retry.js#L159-L163), which is really bad because it may be giving us false confidence.

I think the solution here is to replace `this.request` with `this.request.clone()`, when we pass it to `fetch`.

**Comment by zjr** [comment]
Might be a couple weeks but if I can manage to find the time sooner I will.

**Comment by sholladay** [comment]
Hi @zjr do you think you'll be able to look at this soon? I'd like to fix this in the next patch release along with another v0.16 regression.

**Comment by elijahsmith** [comment]
we are hitting this same issue.

I've just spent several hours trying to reproduce the issue in a test, but had no success.  I did open a small PR to improve the retry tests, by verifying the status text associated with the rejected promises: https://github.com/sindresorhus/ky/pull/229

What I am seeing when hitting this bug in our application is, the first retry returns the correct error -- `HTTPError: Bad Request` in the `beforeRetry` hook's `errors` param -- but then subsequent retries return `TypeError: Failed to execute 'fetch' on 'Window': Cannot construct a Request with a Request object that has already been used.`, just as @zjr describes above.

But for the life of me, I can't reproduce it in a test.  I've tried various permutations of some hooks we have in place; I'm replicating our use case exactly (POST, with an endpoint generating an [intentional] 400 status code); I've tried accessing the error in the `.catch`, etc etc.  I'd be happy to do more work on reproducing this in tests but I'm at a bit of a loss... any ideas?

**Comment by sholladay** [comment]
@elijahsmith thanks for digging into this. I imagine you have been working with the tests in [test/retry.js](https://github.com/sindresorhus/ky/blob/bb46ca86e36d8998c0425ac1fa3b3faf9972c82b/test/retry.js), where everything is run in Node. My recommendation at this point is to write a [Puppeteer](https://github.com/puppeteer/puppeteer) test instead, such as the tests in [test/browser.js](https://github.com/sindresorhus/ky/blob/bb46ca86e36d8998c0425ac1fa3b3faf9972c82b/test/browser.js), where Ky is run in an actual browser (headless Chromium). That may expose the problem to the tests, as the lack of an error may very well have something to do with the `Request` implementation from `node-fetch`, which our Node tests use (imported in [test/_require.js](https://github.com/sindresorhus/ky/blob/bb46ca86e36d8998c0425ac1fa3b3faf9972c82b/test/_require.js#L1)).

In fact, I think a lot of our tests should be updated to use Puppeteer, in order to catch potential issues that are only reproducible in a browser. That would slow down and complicate the tests a bit, but I think the tradeoff is worth it, given that we target browsers and this wouldn't be the first time the Node environment behaved differently.

To compensate somewhat for the slower tests, we _could_ consider switching to the `puppeteer-core` package, which avoids downloading Chromium at `npm install` time in favor of using an existing Chromium / Chrome installation on the machine. I suppose that is feasible given how ubiquitous Chrome is, but still, some developers may not have it. It is also subject to certain limitations (e.g. no support for [config via env vars](https://github.com/puppeteer/puppeteer/blob/v2.1.0/docs/api.md#environment-variables)).
