### ISSUE TITLE
Add default headers without re exporting it everywhere

### ISSUE THREAD

**Issue by KhalilMohammad** [sindresorhus/ky#218]
In axios, it possible to add default headers for all request using

`axios.defaults.headers.common['Auth-Token'] = 'foo bar';`

Does ky has similar future.

Does ky support setting headers via getter setters.
Then we can access them as usual using import.

Using ky extend is cumbersome, as I have to export it everywhere after that.

**Comment by sholladay** [comment]
I am 👎 on changing defaults this way. I much prefer the functional approach.

I don't see how `ky.extend()` is cumbersome. You define your custom instance _one time_, in _one place_. Then, if you have other files that need it, wherever you would've done `import ky from 'ky'`, you instead do `import myKy from './my-ky'` (name it however you want).

The approach that you are proposing involves implicit, magical side effects. One of your files will change the Ky options without other files being aware of it. I really dislike that, especially for something like Ky that accesses the network. I would argue that it's not robust, because then the defaults will be different in various places, depending on the order of your imports. It's a little scary, actually. People working on your app probably have no idea that using Ky will include that header and it will be more difficult to track down the source of it even if they do notice.

Another problem this creates is that there will likely be some situations where you want to use Ky's _original_ defaults and doing so would be tricky. For example, you may want to use certain defaults when calling your own APIs but use the original defaults when calling third-party APIs. We would probably need to have something like `ky.originalDefaults` to fully support that. It is overly complicated.

On the other hand, I do understand why you dislike typing the path to your custom instance. But that's more of an issue with `import` and the module system than Ky. I would urge you to look at [import maps](https://github.com/WICG/import-maps) as a solution. It will let you do `import myKy from 'my-ky'` instead of `import myKy from './my-ky'`. You can already use import maps in [Deno](https://deno.land/) and Ky supports Deno. Hopefully other runtimes will start supporting import maps soon, too. It would appear that the Chromium team is [working on it](https://bugs.chromium.org/p/chromium/issues/detail?id=848607).

**Comment by KhalilMohammad** [comment]
I understand your reasoning but in a custom authentication where authentication takes after a number of steps. After all steps, then I extend ky and use that everywhere. 

This seems cumbersome.

I do not have problem with importing.

**Comment by sholladay** [comment]
So your problem is that you re-export a new Ky instance each time the authentication moves to a new step?

Sounds to me like you should be using a hook to add the header based on the authentication state. That will let you use a `const` and just export one instance that never changes. We have a few examples in the README that are relevant.

**Comment by KhalilMohammad** [comment]
ok, thanks for help.
I will try them.
