### ISSUE TITLE
NormalizedOptions interface giving wrong Headers type

### ISSUE THREAD

**Issue by geoff-harper** [sindresorhus/ky#240]
The issue I'm experience specifically is the options param in the hook functions. I'm trying to set the `Authorization` header with `options.headers['Authorization'] = token` but `NormalizedOptions.headers` claims to be a `Headers` class, when it's actually just a Record of key/value strings like in the `create`/`extend` options.

**Comment by sholladay** [comment]
Yes, I think you're right. In older versions of Ky, we used to normalize the `headers` option and hooks would always receive it as a `Headers` instance. But these days, `headers` is just the raw option given by the user, which is allowed to be a plain object.

The fix is probably just to delete `headers` from the `NormalizedOptions` type definition, as it extends `RequestInit`, which should take care of it for us.

**Comment by geoff-harper** [comment]
That's setting the header on the actual `Request` instance isn't it? My use case is a `beforeRetry` that refreshes the token and retries. If I only set the header on the `Request` instance and not the ky instance, will it still be sent on subsequent requests?

**Comment by sholladay** [comment]
> That's setting the header on the actual Request instance isn't it?

Yes. If you call `request.headers.set()` within a hook, it will only modify the request that the hook is running for. Not sure why that is problematic.

> If I only set the header on the Request instance and not the ky instance, will it still be sent on subsequent requests?

It will be used to perform the request, as we pass the `request` object to `fetch()`. And it will be used for any request where the `request` is cloned and re-used, such as retries.

As for subsequent non-retry requests, of course the `request` is created from scratch so it won't start off with the same headers. But then your hook will run and it will be added again. So in effect, it's the same, no?

If you want to specify a header up front to be added to all future requests, you should do that with an extended Ky instance and the `headers` option, not a hook.

```js
const myKy = ky.extend({
    headers : { authorization : 'foo ' },
    hooks : {
        // ...
    }
});

myKy('/bar');  // will include the authorization header and hooks will receive options.headers as a plain object
```

As I stated earlier, recent versions of Ky no longer normalize `options.headers`. So using the above example, any hooks would receive a plain object. The hooks will only receive a `Headers` instance if you originally constructed it with `new Headers()` in the Ky options, as shown below.

```js
const myKy = ky.extend({
    headers : new Headers({ authorization : 'foo ' }),
    hooks : {
        // ...
    }
});

myKy('/bar');  // will include the authorization header and hooks will receive options.headers as a Headers instance
```

Ky supports both of these syntaxes. Hooks can choose to read those headers from either `request.headers` or `options.headers`. However, to _set_ a header, only `request.headers` should be used. I would recommend using `request.headers` for both get and set, because it's always a `Headers` instance, and thus the interface will be more consistent.

As for the type definitions, like I said, Ky doesn't normalize `options.headers` anymore. SO [this line](https://github.com/sindresorhus/ky/blob/3f8969f8ee022bc16ee40bd7f3f8489c75991919/index.d.ts#L290-L291) should probably be removed, as the hooks can receive a plain object for `options.headers`.

**Comment by geoff-harper** [comment]
> But then your hook will run and it will be added again. So in effect, it's the same, no?

Well if the refreshed token isn't stored in the created ky instance, and only the lifetime of the current request, then that means I will 401/403 on every single request, retry on every request, refresh every request, etc. The token is good for about an hour iirc so I want to use it until it expires instead of adding an extra round trip to every request, extra server traffic, and bloating server logs

**Comment by sholladay** [comment]
> The token is good for about an hour iirc so I want to use it until it expires instead of adding an extra round trip to every request

Well, you have two ways to include that token in the request. As I mentioned, you can either add the token to all requests by making a custom Ky instance with the `headers` option, or you can add it to each request before it is sent by using `request.headers.set()` inside of a `beforeRequest` hook. You can combine these approaches in various ways if needed, too.

Since your token is short lived, perhaps using `beforeRequest` is the way to go. But that is up to you. Another approach would be to call `ky.extend()` each time you get a new token and assign the new instance so it gets used for future requests.

As for how to keep track of the token as it refreshes, again that is up to you. You could do something like this...

```js
let token = '123';

const myKy = ky.extend({
    hooks   : {
        beforeRequest : [
            (request) => {
                request.headers.set('authorization', `token ${token}`);
            }
        ],
        afterResponse : [
            if (response.status === 403) {
                // Get a fresh token
                token = await ky('https://example.com/token').text();
            }
        ]
    }
});
```
Alternatively, you could certainly attach your token to each Ky instance to keep track of it, though I would advise against that if you can avoid it, so as to prevent naming conflicts with any future APIs we decide to add to Ky.

**Comment by geoff-harper** [comment]
Thanks for the detailed breakdown, I guess I'll do it like your last example. I like the idea of just updating the options and having the fresh header picked up automatically for all subsequent calls of that instance but this will still work just fine

**Comment by sholladay** [comment]
Thinking about this some more... Since you were trying to update a nested object _within_ the options object rather than a property of the options object itself, the pattern you originally wanted to use should work, I think. It's just that the TypeScript definitions are out of date.

Most of what I said earlier still stands. Mutating the options object is unsupported, as that object is actually re-constructed on each call of `ky()`. Setting the `credentials` option this way would not work, for example. However, your `headers` object is probably not re-constructed on each call. So mutating it should work. I still would advise against it as mutating external objects is a bad design. I would prefer using `ky extend()` and assigning the result to the variable that holds your instance.

We'll get those type definitions updated, regardless.

**Comment by sholladay** [comment]
@geoff-harper it would be great if you could try my branch in PR #243 and confirm that it fixes your problem
