### ISSUE TITLE
Why does ky throw errors on 3xx responses?

### ISSUE THREAD

**Issue by ciex** [sindresorhus/ky#253]
I am sure there is a good reason for this, please add it to the documentation. 

Particularly for 301 / 302: If a ressource moved to a different location I want a redirect to be followed instead of an error thrown, so this tripped me.

**Comment by sholladay** [comment]
I cannot reproduce. Please show your configuration.

```js
import ky from 'ky';
try {
    await ky('https://httpstat.us/302');
    console.log('successful');
}
catch (error) {
    console.error('unsuccessful:', error);
}
```

We follow redirects by default, same as `fetch`. If you disable redirect following, then yes, Ky will throw for redirects, because [`response.ok`](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok) is `false` in that case, meaning the request was unsuccessful. You can disable `throwHttpErrors` if you wish, but I wouldn't recommend it.

**Comment by ciex** [comment]
Thank you, I will look into it. The readme says

> Treats non-2xx status codes as errors

and redirects are non-2xx status codes. So if they are being followed, that statement is misleading.

**Comment by sholladay** [comment]
Sure, the text could probably be improved. I'm not so sure it is misleading, though. For one thing, not all 3xx responses can be followed, e.g. those without a `Location` header. Further, as I mentioned, it is possible to disable redirect following. Finally, I think the redirect behavior is pretty intuitive (and seems to be what your original post expected, too). The statement rings true in general to me.

We couldn't just say, "except redirects", because then it would be misleading in a different way, due to the cases I mentioned above. HTTP is complicated. To what degree do we want to explain the nuances here?

Would you be satisfied if we added something like, "in most cases, redirects are followed and handled automatically", or does that somewhat vague language raise more questions than it answers? Again, just trying to avoid complicating things, especially for those who aren't well-versed in HTTP. Experts will likely read the source code, regardless.
