### ISSUE TITLE
not get corrrect html

### ISSUE THREAD

**Issue by dverdugo85** [sindresorhus/ky#259]
I hope that  help me   I try to get html from this  Link **:https://www.t13.cl/noticia/tendencias/series-netflix-distopicas-maratonear-26-05-2020**

**I got   the different html** when  use got  and Edge. Don't paste the whole header, I would have to define a user-agent?

 with **got**  I obtain:
```
<head>
 <title>T13 | Tele 13</title>
</head>

```
<head>
<title>6 series (Netflix, Amazon) por si el mundo no vuelve a ser igual | Tele 13 </title>
</head>
```



 with **browser edge** I obtain:
```
<head>
<title>6 series (Netflix, Amazon) por si el mundo no vuelve a ser igual | Tele 13 </title>
</head>
```
I want to read metadata!
Regards!!

**Comment by sholladay** [comment]
Please provide some more info for reproduction:
 - The code you used
 - The version of Ky
 - The headers sent in the request

I'll try to help despite the missing info, though...

> I try to get html from this Link ...

Okay, here is how I would do it:

```js
import ky from 'ky';
const url = 'https://www.t13.cl/noticia/tendencias/series-netflix-distopicas-maratonear-26-05-2020';
const text = await ky(url).text();
console.log(t'HTML:', text);
```

> I got the different html when use got and Edge.

This repository is for **Ky**. If you are looking for **Got**, it is over here: [sindresorhus/got](https://github.com/sindresorhus/got)

The difference is important here because Ky and Got will have different [User-Agent](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent) headers. Ky requests will have the user agent of whatever browser it is running in, whereas Got has a generic default user agent that can be overridden (see the Got docs on its [default user agent](https://github.com/sindresorhus/got#user-agent)). This could affect what content the website decides to return, though it's a bad practice, so hopefully that's not the case.

> Don't paste the whole header, I would have to define a user-agent?

I don't entirely understand what this means, but no, you don't have to define a user agent when using Ky, as the browser will do it for you. But you _should_ define your own user agent when using Got, though you still don't have to because there is a default.

> with got I obtain:
> ```html
> <head>
>     <title>T13 | Tele 13</title>
> </head>
> ```

When I visit the site in Firefox or fetch it with Ky, I also get that title.

> with browser edge I obtain:
> ```js
> <head>
>     <title>6 series (Netflix, Amazon) por si el mundo no vuelve a ser igual | Tele 13 </title>
> </head>
> ```

I don't have easy access to Edge at the moment to verify this. Are you sure it's the same page? And are you saying that's what you see in Edge when you use "View Source" or do you mean that you are using Ky in Edge?

**Comment by sholladay** [comment]
Closing due to lack of response. Happy to re-open if new info comes along.
