### ISSUE TITLE
Include request URL in TimeoutError message

### ISSUE THREAD

**Issue by ByScripts** [sindresorhus/ky#266]
When doing something like this:

    try {
        return api.get('foobar', { timeout: 1 }).json();
    } catch(e) {
        console.log('Error', e); // Never caught
    }

1. <del>The `console` shows a `TimeoutError`... but it is not caught by try/catch (the request is not cancelled and after some milliseconds returns a 200)</del> (missing `await`, see @sholladay comment below)
2. There is no information about which URL has timed out. We are using Sentry to review client error. We have many `TimeoutError` but we are unable to know which URL is concerned.

**Comment by sholladay** [comment]
You are attempting to use `try` / `catch` on a [`Promise`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), but promises don't throw, they _reject_, which is different.

You have two options:
1. Use `.catch(() => { /* ... */ })` instead of `catch (error) { /* ... */ }`
2. Use `await` to "unwrap" thr promise.

Here's an example of the latter:

```js
try {
    return await api.get('foobar', { timeout: 1 }).json();
} catch(e) {
    console.log('Error', e); // Never caught
}
```

As for reporting the URL of the timed out request, that seems like a reasonable thing to add. I'm not sure if the URL was intentionally omitted or not. We'll need to consider the implications of including potentially untrusted data in our error messages, but I think it should be fine.

**Comment by ByScripts** [comment]
You're right, I forgot the await when writing my example on CodeSandbox, sorry for that.
