### ISSUE TITLE
parseJson() is not called in AfterResponseHook

### ISSUE THREAD

**Issue by kirillgroshkov** [sindresorhus/ky#275]
This is a follow-up bug after using `parseJson` functionality in production (related to https://github.com/sindresorhus/ky/pull/272).

`parseJson` works like charm everywhere, except in `AfterResponseHook`.

Simplified code:
```typescript

const ky = ky.extend({
  parseJson: text => JSON.parse(text, someReviver),
  hooks: {
    afterResponse: [{
      async (_req, _opt, res) => {
        const data = await res.json()
        console.log(data) // HERE the parsed object is NOT revived (not passed via `parseJson` function)
      }
    }]
  }
})

```

So, we should handle such case and add a test for it.

**Comment by sholladay** [comment]
This happens because we call `response.clone()` before passing it to the hook.

We could make an internal `decorateResponse` function and call it where necessary to add the custom parser. The code is going to be kind of messy, though. I wish there were a better way to do this.

**Comment by sholladay** [comment]
No

**Comment by juliushuck** [comment]
I also use the parseJson option to revive dates.

When I call response.json() in an after response hook, I get the error that the response body can only be consumed once. I think because, the response that gets returned from my hook get set to the response object above the after response hooks for loop in the core/ky.js code.

My current solution is to use this in my after response hook: options.parseJson(await response.clone().text())

Is that the preferred way?

**Comment by abdurrahmanekr** [comment]
parseJson function that I added to instance is solves problem.

```ts
import ky from 'ky';
import modifyObjStringToDate from "@/lib/utils/modifyObjStringToDate";

const prefixUrl = `${API_URL}/`;

export const instance = ky.extend({
  prefixUrl,
  headers: {
    Accept: 'application/json',
  },
  parseJson(jsonStr) {
    try {
      const data = JSON.parse(jsonStr);
      modifyObjStringToDate(data);
      return data;
    } catch (e) {
      return jsonStr;
    }
  }
});
```
