### ISSUE TITLE
[vite] dependency ky does not have default entry defined in package.json.

### ISSUE THREAD

**Issue by niicojs** [sindresorhus/ky#282]
When used with `vite`, I get a "[vite] dependency ky does not have default entry defined in package.json.".
Does not seems to be a blocking issue, but it's an easy fix :)

**Comment by sindresorhus** [comment]
I have no idea what Vite is, but that is a problem with Vite. Ky works fine for other tools and is doing everything correctly. I would recommend opening an issue over at Vite instead.

**Comment by sholladay** [comment]
Should be reported here:
https://github.com/vitejs/vite

**Comment by niicojs** [comment]
The issue is probably that there is no "main" defined in package.json. I really don't think that something I should report to the bundle repo.

**Comment by sindresorhus** [comment]
@niicojs No `main` is allowed if the main file is named `index.js`. This is according to the package.json spec.

**Comment by sholladay** [comment]
The reason why Ky doesn't specify `main` is because we use the default, which is `index.js`. This is a convention for the entire Node.js platform. It has nothing to do with Ky. So your issue belongs on either the Node.js issue tracker or the Vite issue tracker, depending on how you look at it. You could try to convince the Node team to make `main` required or change the default value, in which case we will follow suit. But I suspect you'll have more success in convincing the Vite team to go along with how Node.js works. And it sounds like that is sort of already the case, since the message you're getting is a warning rather than an error. But what's the purpose of the warning? Why is Vite warning about it to begin with? Only the Vite team can answer that. While I'm not too familiar with Vite, as far as I can tell there is no purpose. It's just noise polluting your terminal, probably for no particular reason.

**Comment by prem-prakash** [comment]
@niicojs it is probably even already solved, see https://github.com/vitejs/vite/commit/5969c97ab5d0da56be72083d88b583db109fd3d3
