### ISSUE TITLE
add "main", "module" and "types" field

### ISSUE THREAD

**Issue by rifler** [sindresorhus/ky#283]
Because `ky` delivers index.js in esm format and untranspiled, it generates a bit of a problem for "universal" applications

If I use `ky/umd` it works well in node and client, until I want to transpile all of my node_modules, to support old browsers.
After that babel+webpack breaks about `ky/umd` (i haven't figured out the reasons yet)

decision - add these lines to package.json:
```json
"main": "./umd.js",
"module": "./index.js",
"types": "./index.d.ts",
```

explanation:
user will impor just `ky`. Node.js will see `main` field, will require `ky/umd` and won't break about esm. Bundlers like webpack and others will see `module` field and will bundle index.js (esm format).

Transpiling remains on the user's side

Maybe it partially related to https://github.com/sindresorhus/ky/issues/255

**Comment by sholladay** [comment]
I would be fine with this if it actually worked everywhere, but I believe `module` is not as widely supported as you might think, including by Node.js itself and its new ESM loader.

We have what I think is a more forward thinking approach in PR #244 but unfortunately that work has stalled due to some configuration problem in our testing stack that I wasn't able to track down quickly. You could help by looking into that.

**Comment by rifler** [comment]
> I would be fine with this if it actually worked everywhere, but I believe module is not as widely supported as you might think, including by Node.js itself and its new ESM loader.

"Module" widely supported by bundlers, first of all it is webpack and rollup.

But I think that this issue and #244 are not competitors and complementing each other:
`main` - for old versions of node & bundlers. It is CJS
`module` - for bundlers that supports this field, webpack < 5, rollup, etc. It is ESM
`exports` - for new versions of node and bundlers (webpack >= 5). It is dual mode (esm & cjs)

**Comment by sholladay** [comment]
I believe that would break our CDN users who load Ky from `https://unpkg.com/ky`, for example. They would start receiving UMD instead of ESM, which I personally consider unacceptable for a browser oriented library. If `unpkg.com` preferred `module` over `main`, then it would be fine. But I don't think it does.

**Comment by rifler** [comment]
@sholladay can you please provide an example? I'll check that

**Comment by rifler** [comment]
@sholladay You are right, I fixed this behaviour in #284

**Comment by sholladay** [comment]
There are a lot of other CDNs to test, though. I really think it would be better to "default" to ESM with `main` and then fix the Node.js case with `exports`. I'll play around with this and see how it goes, though.

**Comment by rifler** [comment]
jsdelivr ok:
https://cdn.jsdelivr.net/npm/rifler-test-package

> and then fix the Node.js case with exports

will it work if host program is in cjs mode? will it work in all versions of node?

**Comment by rifler** [comment]
All I want to say, that current selected way (main is esm) is very uncommon and breaks many scenarios

ecosystem is not ready yet for this

in the next few days I will create fork of ky (if this PR will not merge), and I feel sad about it

**Comment by sindresorhus** [comment]
The correct solution is https://github.com/sindresorhus/ky/pull/244
