### ISSUE TITLE
Any plan/interest to rewrite in TypeScript?

### ISSUE THREAD

**Issue by mgcrea** [sindresorhus/ky#321]
Seeing that got is now 100% typescript, is there any plan or ongoing effort on porting this sister project to TypeScript?

**Comment by sholladay** [comment]
I'm personally on board with this. It would certainly be nice for Deno users, as it would remove the need to manually import the types.

**Comment by sindresorhus** [comment]
I'm not sure I want that. The Got rewrite to TS ended up being a nightmare. TS just so buggy.

**Comment by sindresorhus** [comment]
> as it would remove the need to manually import the types.

Why would you need to manually import the types? Can Deno really not infer it automatically?

**Comment by sholladay** [comment]
Deno imports modules directly from URLs. They have an excellent on-disk caching system so things get loaded from the file system when possible but they've made a design choice to not probe servers for `.d.ts` files for every new `.js` request. I get it, honestly. Those HTTP requests aren't free.

There _is_ an HTTP header that CDNs can use to explicitly point Deno to the TS types and it will then load them automatically. That's what the `?dts` query parameter on the Skypack CDN does, which we recommend to Deno users in the readme. So I wouldn't say this is a big deal. But it would be nice if Deno users could just load an `index.ts` file from any CDN and not have to worry about those details.

**Comment by mgcrea** [comment]
> I'm not sure I want that. The Got rewrite to TS ended up being a nightmare. TS just so buggy.

I can't attest for the ongoing maintenance burden of got as a TS project but as someone that was pretty reluctant to migrate both personal projects and published libraries to TS, I really find that it ends up being a pretty big net positive in both development speed and overall robustness of the code.

Also since `ky` does not have any dependencies and `Fetch` related API must be pretty stable now. I don't think there would be much external TS-related burden.

Anyway, as maintainers it is your call to make. But if you reconsider it in the future, I could spend some time on it and give it a try and see how it goes.

**Comment by sindresorhus** [comment]
There are multiple things:

- TS broke something in pretty much every minor release (from talking to people, this is a common occurrence).
- Node.js types are often outdated or incorrect. The situation might be better for DOM since it's now auto-generated.
- Tooling is annoying. We cannot move to ESM because AVA (test runner) doesn't yet support ESM with TS.
- Bloated package because of all the `d.ts` files.
- https://github.com/sindresorhus/got/issues/1137
- We have encountered a myriad of TS bugs where we end up on an old unresolved issue on the TS issue tracker. A pretty common occurrence.
- TS is not even type-safe. They're only finally getting around to making `array[1]` include `undefined`.

Yes, there are obvious benefits too. TS linting has helped fix a lot of code. Refactoring is so much easier. Automatic `.d.ts` types. Etc.

That being said. Ky is considerably simpler than Got, so if any of you feel strongly about this and are willing to do the work, I will not be in your way.

**Comment by Richienb** [comment]
How would we type `deepMerge`?

https://github.com/sindresorhus/ky/blob/110aba869a1a2cf1f1d7775c033fde141e600508/index.js#L24

**Comment by Genarito** [comment]
Even if you put some general type as `any[]` for sources you could get some benefits like removing `Array.isArray(...)` as Typescript is checking that.
With a fast check I could say that: 

1. headers:  {[key: string]: string}[]
1. sources could be force to be always an array, so you could prevent the `isArray/isObject` if/else as it's used internally. But the recursive part should be removed. It would be cool if there were JS docs about what's doing that function

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/ky/pull/330
