### ISSUE TITLE
POST request doesn't have body for Tizen 2017

### ISSUE THREAD

**Issue by Beraliv** [sindresorhus/ky#338]
I have options like this one:

```ts

const kyOptions = {
    headers: {
        'Authorization': "Bearer <token>",
    },
    json: {
        content_id: "<id>"
        content_type: "<type>"
    },
    method: "post"
};
```

Then I call `ky`:

```ts
const response = ky(uri, kyOptions);
```

And I have error as somehow `fetch` was called without `body`. If I replace the call with `fetch` itself, the request will be sent correctly as expected:

```ts
const response = await fetch(uri, {
   body: JSON.stringify(kyOptions.json),
   headers: {
      'Content-Type': 'application/json',
      ...kyOptions.headers,
   },
   method: 'POST'
});
```

Do you know why this can happen?

I use `whatwg-fetch` and `core-js`, maybe also something is missed?

**Comment by sholladay** [comment]
Can you please specify which Ky version you are using?

Your code looks fine to me, but here are some things to try for debugging purposes:
 - Use `'POST'` in uppercase. Ky normalizes method casing, but I see it's different between your two examples.
 - Use the `body` option with Ky, instead of `json`.
 - Put the body in a [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) instance and pass that to Ky as the first argument.

**Comment by Beraliv** [comment]
@sholladay thank you, will check it tomorrow

**Comment by Beraliv** [comment]
> Use 'POST' in uppercase. Ky normalizes method casing, but I see it's different between your two examples.

I checked, inside it has `method: "POST"` ✅

> Put the body in a Request instance and pass that to Ky as the first argument.

So step by step I have this:

```ts
// 1. after this.request = new globals.Request(this._input, this._options); ✅
{
bodyUsed: false
credentials: "same-origin"
headers: Headers {}
integrity: ""
method: "POST"
mode: "cors"
redirect: "follow"
referrer: "about:client"
url: "<url>",
}

// 2. after if (this._options.json !== undefined) { block
// 2.1. put stringified { content_id: "<id>", content_type: "<type>" } into this._options.body as expected ✅
// 2.2. put 'content-type', 'application/json' into this.request.headers ✅
// 2.3. after updating request I see the problem ❌ this.request equals to:
{
bodyUsed: false // <== why? 🤯
credentials: "same-origin"
headers: Headers {}
integrity: ""
method: "POST"
mode: "cors"
redirect: "follow"
referrer: "about:client"
url: "<url>"
}
```
Also `this.request.body` is `undefined

**Comment by Beraliv** [comment]
I tried this in Chrome, it will show me value:

```js
const request = new Request(request2, { body: JSON.stringify({ a: 1 }) }); 
request.json().then((body) => console.log('>>> body: ', body));
```

However on Tizen 2017 I cannot see the result 🧐

Do you have any ideas?

**Comment by sindresorhus** [comment]
> Tizen 2017

What Chrome version does it use?

**Comment by Beraliv** [comment]
> > Tizen 2017
> 
> What Chrome version does it use?

It doesn't match exactly the version of Chrome

But something closely to Chrome 25-30 😝

**Comment by Beraliv** [comment]
And yes, in caniuse it says it's available since Chrome 42

https://caniuse.com/mdn-api_request

**Comment by sholladay** [comment]
Which Ky version?

> Also this.request.body is undefined

There is no such thing as `request.body`. If you want to access the contents of a request's body, you need to use one of the body methods, such as `.text()` or `.json()`.

```js
this.request.text().then(console.log)
```
I suggest adding that after [this line](https://github.com/sindresorhus/ky/blob/bf5be2f27b614ae632285d995e2b7dcfec985bcd/source/core/Ky.ts#L89) or maybe [this line](https://github.com/sindresorhus/ky/blob/bf5be2f27b614ae632285d995e2b7dcfec985bcd/source/core/Ky.ts#L108) or other parts of the Ky codebase to figure out where the first place is that `.text()` doesn't work. Note that when you add that debugging code, you'll start seeing a "body has already been consumed" error, because calling a body method consumes the stream and then it can't be read anymore when Ky tries to do the actual fetch.

In particular, check before and after each place where we do `request.clone()`.

**Comment by Beraliv** [comment]
@sholladay 

> Which Ky version?

"ky": "0.25.1",
"ky-universal": "0.8.2"

> There is no such thing as `request.body`. If you want to access the contents of a request's body, you need to use one of the body methods, such as `.text()` or `.json()`.
> 
> ```js
> this.request.text().then(console.log)
> ```

Yeah, I already checked it here – https://github.com/sindresorhus/ky/issues/338#issuecomment-834366020 but it wasn't working on Tizen 2017 at all

> I suggest adding that after [this line](https://github.com/sindresorhus/ky/blob/bf5be2f27b614ae632285d995e2b7dcfec985bcd/source/core/Ky.ts#L89) or maybe [this line](https://github.com/sindresorhus/ky/blob/bf5be2f27b614ae632285d995e2b7dcfec985bcd/source/core/Ky.ts#L108) or other parts of the Ky codebase to figure out where the first place is that `.text()` doesn't work. Note that when you add that debugging code, you'll start seeing a "body has already been consumed" error, because calling a body method consumes the stream and then it can't be read anymore when Ky tries to do the actual fetch.
> 
> In particular, check before and after each place where we do `request.clone()`.

I think the main problem that native Request doesn't support it and Promise isn't resolved at all

**Comment by Beraliv** [comment]
@sholladay @sindresorhus thank you for the help! I really appreciate you spent some time on it

**Comment by sholladay** [comment]
No problem, glad you found a solution! I wonder if the way that polyfills are set up in [ky-universal](https://github.com/sindresorhus/ky-universal) would work for you, so that you don't have to do that in your own code. Might be worth trying `ky-universal`, if you're not already using it.

**Comment by Beraliv** [comment]
@sholladay I think that's the main problem for Tizen 2017 at the moment

It has some native support for `fetch` which do NOT support `Request`. That's why I need to identify the device and delete native fetch

It helps
