### ISSUE TITLE
The `credentials` field on `RequestInitializerDict` is not implemented; Cloudflare Workers issue.

### ISSUE THREAD

**Issue by TimTinkers** [sindresorhus/ky#366]
I am experiencing the same issue with credentials that prevents `ky` from being used with Cloudflare Workers that `redaxios` is also [experiencing here](https://github.com/developit/redaxios/issues/64).

**Comment by TimTinkers** [comment]
Never mind, it could be that I am just supposed to manually override the credentials in such case as was previously discovered on the Cloudflare Workers Discord server.

![meme](https://user-images.githubusercontent.com/2444641/128486410-8df850ee-9c56-43f1-899a-0de8fbace43b.PNG)

**Comment by sholladay** [comment]
I suppose we could internally feature test the field. Not ideal, though. Did setting it to `undefined` work for you?

**Comment by aroman** [comment]
any progress on this? ky works fine in cloudflare workers environment, but this type error makes it so i need to use skipLibCheck

**Comment by sholladay** [comment]
The fix for this is likely trivial once someone who uses Workers steps in to help.

We need to guard [this line](https://github.com/sindresorhus/ky/blob/356d61c1534c9dc2cfb8ce1c1ff5c4832579e11b/source/core/Ky.ts#L122) to avoid setting `credentials` if it is unsupported.

My first guess about how to do so is:

```js
const isCredentialsSupported = 'credentials' in Request.prototype;
```

That resolves to `true` in browsers. Hopefully it resolves to `false` in Workers. Could someone who uses Workers please confirm?

**Comment by zanechua** [comment]
@sholladay it does resolve to `false` indeed.
