### ISSUE TITLE
Universal app

### ISSUE THREAD

**Issue by hrasoa** [sindresorhus/ky#37]
I know we should use [Got](https://github.com/sindresorhus/got) for node js, but I'm building an universal app that will be rendered on both server/client side, so how should we handle that ?

**Comment by sholladay** [comment]
I suspect you will have an easier time Browserify-ing  `got` than doing the inverse with `ky`.

**Comment by szmarczak** [comment]
It depends on what functionalities you are trying to implement. Got provides more functionalities than Ky because Node is a little bit more advanced. I don't recommend using a wrapper because of the differences between them. Use Got when you're targeting Node and use Ky when you're targeting browsers :)

**Comment by bkniffler** [comment]
I think a lot of people will not be able to "just use both" since if you have a universal react app that fetches data or you write shared libraries for server and client to talk to your API, its much easier to just use axios which can be used on both sides. I don't get why it is so hard to make ky universal/isomorphic though, for node-fetch and isomorphic-fetch exists.

**Comment by sholladay** [comment]
@bkniffler when it comes to the basic stuff, sure, an isomorphic approach works. But I absolutely need relative URLs, which `node-fetch` does not support because there is no base URL there. Also, the whole concept of a Referer doesn't really work in Node. Conversely, Node has more mature support for streams since it has been around longer - the abstractions in browsers will be better when they are fully implemented, but we aren't there yet.

I think you will find that if you start using some of the more intermediate/advanced features of these HTTP clients, the isomorphic approach starts to look less and less feasible. I do believe we will get there one dsy, but it's going to take some more spec work at W3C and WHATWG first. Otherwise, libraries will just continue to fake it with lots of inconsistencies and gaps in functionality, which is the current status quo.
