### ISSUE TITLE
Headers are not sent when mode is no-cors

### ISSUE THREAD

**Issue by Nisgrak** [sindresorhus/ky#406]
If the mode has been set to `no-cors` the headers won't be sended.

I create a example stackblitz
1. Open this in other window https://beeceptor.com/console/test-ky (this logs the requests in the stackblitz example)
2. Open https://stackblitz.com/edit/js-zatpf9?file=index.js
3. Go to first openend window (beeceptor)
4. Check the headers of the two request, with-cors have x-api-key header and whitout-cors doesn't

![image](https://user-images.githubusercontent.com/19597708/146185464-2df0571e-4791-43c5-b0ca-3a5a7313fbfb.png)
Normal mode
![image](https://user-images.githubusercontent.com/19597708/146185588-c7144afb-a63e-45f3-a20b-6135249a6351.png)
No-cors mode
![image](https://user-images.githubusercontent.com/19597708/146185552-f4922101-c1fb-4bf3-a16b-cad19bf6de5c.png)

**Comment by sholladay** [comment]
Thank you for the great reproduction steps. This is not exactly a Ky issue but it's worth exploring.

I say that because I can reproduce the same behavior with just plain `fetch`, without Ky.

https://stackblitz.com/edit/js-mcdq89?file=index.js

Looking at section 2.2.5 of the fetch standard, I can see why.

https://fetch.spec.whatwg.org/#concept-request-mode

> "no-cors"
Restricts requests to using [CORS-safelisted methods](https://fetch.spec.whatwg.org/#cors-safelisted-method) and [CORS-safelisted request-headers](https://fetch.spec.whatwg.org/#cors-safelisted-request-header). Upon success, fetch will return an [opaque filtered response](https://fetch.spec.whatwg.org/#concept-filtered-response-opaque).

So, this is working as intended because the default `mode` for `fetch` is `'no-cors'` and that setting restricts requests to using CORS-safelisted request headers, and `x-api-key` is not among them.

The only relevant thing that we could perhaps do in Ky would be to use a different default `mode`.

Interestingly, the fetch standard specifically calls out `'no-cors'` as an unsafe mode, so it's definitely worth considering other options.

> Even though the default [request](https://fetch.spec.whatwg.org/#concept-request) [mode](https://fetch.spec.whatwg.org/#concept-request-mode) is "no-cors", standards are highly discouraged from using it for new features. It is rather unsafe.

So, should we continue using the same default as `fetch` or should we diverge here? Personally, I'd be happy for us to use `'same-origin'`, which causes an explicit error to be thrown for cross origin requests instead of this magical behavior.

**Comment by sholladay** [comment]
Ky's default is actually `cors`. So either way, setting `no-cors` is opt-in and this is just a natural consequence of that decision.

For anyone who runs into this, try to get the server to respond with CORS headers.
