### ISSUE TITLE
Recent versions of ky are not published to deno.land/x

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/ky#409]
Deno's official website provides a [Third Party Modules](https://deno.land/x) service (deno.land/x). As of now ky is the 11th module with most stars in the index, however the latest version stopped at [0.23.0](https://deno.land/x/ky@v0.23.0) (`2020-07-29T20:34:29.818Z`, about a year and half ago).

What's the status of the ky module on deno.land/x? Do the new versions stopped being released there due to mistakes? Given its (potential) popularity it should probably be restored then.

If it is not maintained there anymore, please provide some clear message/suggestion on how people should import ky in Deno.

**Comment by sholladay** [comment]
Our support for Deno continues to be maintained, but unfortunately Ky was published to the Deno registry by someone else in https://github.com/denoland/registry/pull/46. I was preparing my own PR to add it to the registry when I noticed that person had beat me to it by a few hours. So at the moment we can't fix it. I believe the reason that the version is stale on there is due to changes on the registry's backend. IIRC, it used to immediately check for new versions if a version wasn't specified in the URL, but to improve performance they now require an explicit update via a webhook. There's also now a minimum length of 3 characters for module names, at least for new modules. I assume new versions of Ky would continue to be grandfathered in under the old rules, but that's also a potential issue.

I'll ask the Deno team to transfer the name to us and then we can set up the webhook to automatically publish new git tags. Should be an easy fix once we have control over the name.

**Comment by kidonng** [comment]
That someone else is in the Deno team, just to note. Thanks for the explanation, I'm aware of the registry changes and the timepoint seems to match.

**Comment by sholladay** [comment]
@sindresorhus so we need to add a webhook to the repo as described [here](https://dev.to/craigmorten/how-to-publish-deno-modules-2cg6). I lack the permissions needed to add a webhook, could you take care of it?

**Comment by sindresorhus** [comment]
> could you take care of it?

Done

**Comment by sindresorhus** [comment]
https://deno.land/x/ky@v0.30.0
