### ISSUE TITLE
`beforeError` hook

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/ky#412]
Like Got: https://github.com/sindresorhus/got/blob/main/documentation/9-hooks.md#beforeerror

**Comment by ma101an** [comment]
@sindresorhus I tried to give this a go as I initiated the discussion reg this (#411 )

**Comment by gamelaster** [comment]
Does beforeError decodes body? In example, it looks like that, but my error.response.body is ReadableStream. Thanks

**Comment by sholladay** [comment]
Hi, @gamelaster. No, as currently implemented, `beforeError` will always receive an [`HTTPError`](https://github.com/sindresorhus/ky/blob/main/source/errors/HTTPError.ts) instance and while it has a [`response`](https://developer.mozilla.org/en-US/docs/Web/API/Response), the `body` of the response is just an unparsed stream. You can call `error.response.json()` to get a parsed JSON representation of the body.

Looking at the `beforeError` example in our documentation, it could definitely use some improvement.

1. As you saw, the code has a bug where it assumes `body` is an object with a `message` property. This is just wrong.
2. I think we should make it more explicit that network errors (i.e. those that lack a `response`) are never passed to `beforeError`. Having this documented should encourage people to give us feedback if they find that confusing.
3. Since `beforeError` only receives `HTTPError`s and not network errors, strictly speaking, there is no need for the `if (response)` check. Even the `response.body` check is probably not needed, since you wouldn't generally access `response.body` directly, unless you want to operate on it as a stream. Also, I think even if a server responds without a body, `fetch()` would return a response whose `body` is an empty stream instead of `null`. The empty stream would be truthy, making this check pointless, if I am right.

> it might be handy to be able to return full own error instead of modifying HTTPError

While the docs do say you should return an `HTTPError`, and doing so is probably a good idea, I don't see any technical reason you couldn't return a different type of `Error` instance. Perhaps that line in the docs should be changed, too.

**Comment by uchihamalolan** [comment]
@sholladay @gamelaster 
1. My bad, I copied example code from `got` docs where It would send a JSON data with message property
2. Yes, network errors would not trigger beforeError hooks

| it might be handy to be able to return full own error instead of modifying HTTPError

afaik, It should not be a problem.
In case where you would run multiple `beforeError` hooks, the modified error would be passed on to next subsequent hooks and finally the error returned from last hook is thrown which then would not be instance of `HTTPError`. You would need to be aware of that.

**Comment by gamelaster** [comment]
Thank you @sholladay and @uchihamalolan for fast reply!

Yes, the documentation confused me about that the body looked like already decoded, but `response.json()` works just fine, just though I'm doing something wrong 😊 

I tested my custom errors and in the end, find out that I can throw my error even `afterResponse` hook which was totally sufficient for my usage. Thank you once again, ky is amazing! 😊
