### ISSUE TITLE
Using "Retry-After" with error code 425 is impossible

### ISSUE THREAD

**Issue by yaaax** [sindresorhus/ky#473]
Hi there,

I would like to change the way the retries are made. For example: wait 1s before each retry.

One option is to [add a `retry.backoffLimit` option](https://github.com/sindresorhus/ky/pull/454)
Another (by the time the PR is merged) would be to use the `Retry-After` header from the server.
But unfortunately I can make it work with the `425` error code given by the server.
It looks like the `afterStatusCodes` option, set by default to `[413, 429, 503]` cannot be changed.
I've tried these retry options :
```
retry: {
  limit: 12,
  afterStatusCodes: [425],
  statusCodes: [425],
}
```
The code I'm looking at is here: [(Ky.ts) _calculateRetryDelay l.217](https://github.com/sindresorhus/ky/blob/430486b5522dcafd2d658ab391c6a37d921d66da/source/core/Ky.ts#L217)

`afterStatusCodes` is not in the docs… but I found it reading the code and in [that article](https://golb.hplar.ch/2019/08/ky.html)

Any help is welcome

**Comment by mahnunchik** [comment]
Allowing to override `afterStatusCodes` would be really helpful.

Current implementation doesn't allow to override it: https://github.com/sindresorhus/ky/blob/53ce279c818998ed372822207b967eb68b92fba6/source/utils/normalize.ts#L39-L43

Removing line 42 will fix the issue.

**Comment by Kenneth-Sills** [comment]
Curious what the use-case here was. 425 status codes are really a part of the initial handshake process and should be handled by either the browser/Node themselves through an immediate connection reset as specified in [8470 section 4](https://datatracker.ietf.org/doc/html/rfc8470#section-4) and demonstrated in [the Firefox implementation](https://hg.mozilla.org/mozilla-central/rev/7df0e32add4c#l2.59). A 425 falling down into the JS seems like it would indicate a configuration issue or bug in the server/environment.

Of course, allowing users to set `afterStatusCodes` is still a good idea. Especially since it's broadcast as [part of the public type interface](https://github.com/sindresorhus/ky/blob/d042b0575fbdea681031ab39d33b9512e1c4d559/source/types/retry.ts#L23).

**Comment by mahnunchik** [comment]
@sindresorhus ping

**Comment by Kenneth-Sills** [comment]
@mahnunchik The maintainer responds more to PRs than to issues (they have... uh... *a few* repositories). In the next month or so I can probably get to this; unless you beat me to it, of course. 😄

**Comment by sholladay** [comment]
Is it possible for `fetch()` to return a 425? I agree with @Kenneth-Sills, this seems like it ought to be out of scope. But I’m okay with the above mentioned solution if it’s indeed possible for `fetch()` to handle it.

If so, you should be able to implement this already with a `beforeRetry` hook.

We `await` hooks before doing the retry. So just  return a promise that resolves when you want us to retry. For example, wrap`setTimeout()` in a promise and use `error.response.headers` to get the `Retry-After` value for the timeout.

**Comment by Kenneth-Sills** [comment]
Ah, tracing back the origin of that offending line, it seems there was actually [a discussion](https://github.com/sindresorhus/ky/pull/110/files/0b30280ba06ca4ab8a2cfdf5b2a1cf1d26d9613b#r266529193) about this very thing back in 2019:

>**Q:** Should this be exposed?
> **A:** No... We have not exposed it in Got either and no one has requested it yet.

But we did end up accidentally exposing it, and seems like the article OP linked has at least a couple of users thinking it's a part of the intended public interface. This also means IDE autocomplete for TS has been broadcasting this "customizable" property for the whole time.

In light of that, I still think it's best to just let users overwrite the property instead, rather than going through the trouble to artificially impose an `Exclude` on the options they're allowed to pass in. It's one line and some documentation, after all.

----

[Relevant PR Created](https://github.com/sindresorhus/ky/pull/598).
