### ISSUE TITLE
Uncaught (in promise) TypeError: Response.json: Body has already been consumed.

### ISSUE THREAD

**Issue by YoussefZidan** [sindresorhus/ky#479]
After using the **beforeError** hook, what should I do to get the server-generated error? 

the case as the following:

I use the "beforeError" hook as: 

```js
      beforeError: [
        (err) => {
            err.response.json().then((er) => {
              console.log(er.message)
            });
          return err;
        },
      ],
```

then I use the **extended** ky in a component and I catch the error as the following. 

```js
.catch (err => {
    console.log(er);
  }
}) 
```
the above print the HTTP error from Ky.ts
```
HTTPError: Request failed with status code 400 Bad Request
    HTTPError HTTPError.ts:15
    fn Ky.ts:42
    create Ky.ts:70
    method index.ts:16
    postFormData index.jsx:220
    onSubmit index.jsx:244
```
I did the following in order to accomplish my goal of printing the message as I did in the hook. 

```js
.catch (err => {
  err.response.json().then((er) => {
    console.log(er);
  });
  }
}) 
```
but it throws the following error
```
Uncaught (in promise) TypeError: Response.json: Body has already been consumed.
```

**Comment by Caesarovich** [comment]
As in the docs:
```js
beforeError: [
	error => {
		const {response} = error;
		if (response && response.body) {
			error.name = 'GitHubError';
			error.message = `${response.body.message} (${response.status})`;
		}

		return error;
	}
]
```
This hook should normally be used to add/edit properties to the `HTTPError` instance.
In your example you effectively consume the Body by doing `err.response.json()`. Which reads the data and consumes it, because for some reason I wont detail here, the buffer is read only once. If you really want to use the response body twice (In the hook and when catching), you should consider using [`.clone()`](https://developer.mozilla.org/en-US/docs/Web/API/Response/clone) like so: `err.response.clone().json()`. I've tried it and it works.

As this is not an error directly related to ky I suggest we can close this issue if my answer was satisfactory.

Have a good day :+1:

**Comment by YoussefZidan** [comment]
> 

It Worked!
Thank You!!
