### ISSUE TITLE
ky in the vite environment request hint cors.

### ISSUE THREAD

**Issue by lihe6666** [sindresorhus/ky#521]
ky in the vite environment request hint cors.

ky version: 0.33.3
vite version: 4.4.9

error

![1692685302201](https://github.com/sindresorhus/ky/assets/2598007/b529e1a9-ca40-499c-8200-589a6f301b13)

vite.config.ts

![1692685364053](https://github.com/sindresorhus/ky/assets/2598007/d6e3c8bb-f7a8-4ed7-b330-595fe4b30e00)

but, i use fetch is correct

i will headers remove from ky.create and add attribute mode = 'no-cors'

![1692688019737](https://github.com/sindresorhus/ky/assets/2598007/61c33a17-2cae-4e93-81ca-f875e6d43118)

**Comment by marpme** [comment]
In order to make use of your proxy, your request **URL must be relative**. 

So instead of making the request with `ky.get("http://my.live.server.com/smallApps/)`, you can make use of `ky.get("/smallApps/")`.

This would mean in local-development the request goes to `http://localhost:5147` and is handled by your proxy and in production (assuming it's running the same domain) the request goes `http://my.live.server.com`.

if you want to configure the base URL manually (via JS), you can make use of [`ky prefix-url` option](https://github.com/sindresorhus/ky?tab=readme-ov-file#prefixurl)
