### ISSUE TITLE
feature request: errors as returned values

### ISSUE THREAD

**Issue by mAmineChniti** [sindresorhus/ky#624]
i'm suggesting that a really good way of handling errors is returning errors as the first value in a tuple
which will make ky usage more like this
```ts
import ky from 'ky';

const [error, json] = await ky.post('https://example.com/', {
    json: {
        foo: true
    }
}).json();

if (error != null) {
    throw new error;
}

console.log(json);
```
and in case you want to ignore the error you can just:
```ts
import ky from 'ky';

const [, json] = await ky.post('https://example.com/', {
    json: {
        foo: true
    }
}).json();

if (json != null) {
    console.log(json);
}
```
this approach will make error handling a first class idea in devs minds who are using ky and can result in better cleaner code with better error handling and less mistakes and crashes

**Comment by sholladay** [comment]
You've been looking at [safe assignment](https://github.com/arthurfiorette/proposal-safe-assignment-operator), haven't you? 😀

I am glad this pattern is getting so much attention. I would love for JS to become more functional.

However, something that isn't being talked about enough is that, on its own, widespread use of the safe assignment pattern (with or without the new syntax) is going to lead to very messy code. The same way callbacks and even promises could get messy before async await came along.

We are going to need a concise way to prevent downstream functions from running if an error has occurred and perhaps a way to pass errors up multiple layers in the stack. Basically all the same things that `throw` does but in a more functional style. Otherwise, we are going to end up with `if` statements and tedious error passing all over the place. Functional languages tend to have some kind of function folding or pipelining that handles this behind the scenes.

Without that, we are basically back to how `fetch` works by default, where it returns HTTP errors rather than throwing them. And it's not fun because there is no concise way to guard downstream code. Thus, throwing errors is one of Ky's main features, because it allows downstream code to only deal with the happy path.

**Comment by sindresorhus** [comment]
This is something that should be solved by the language, not every package.
