### ISSUE TITLE
ky.extend prefixUrl usage error

### ISSUE THREAD

**Issue by indatawetrust** [sindresorhus/ky#66]
[![Screen-Shot-2018-11-29-at-14-57-31.png](https://i.postimg.cc/d1Gjf8Rr/Screen-Shot-2018-11-29-at-14-57-31.png)](https://postimg.cc/625Z24mp)

with this usage I get the above error

```js
const SERVICE_API = 'http://localhost:4000';

const api = ky.extend({prefixUrl: SERVICE_API});

const json = await api.post(`/connect`, {json: params}).json();
```

**Comment by sindresorhus** [comment]
I think the error message is pretty clear and it's also documented in the readme, so I'm not really sure what this issue is about. It should be:

```diff
-const json = await api.post(`/connect`, {json: params}).json();
+const json = await api.post(`connect`, {json: params}).json();
```

**Comment by indatawetrust** [comment]
very true. I apologize for this nonsense :(

**Comment by lohfu** [comment]
@sindresorhus why was this behaviour implemented? ie why can the input not start with a `/` when using the prefix URL option?

i'm currently passing a fetch instance as the extra argument to my redux thunks to make testing and SSR easier... i am trying to move to ky and was hoping passing an extended version with a prefixUrl option would work, but since all my requests are made to `/api/cars` or similar they all fail.

**Comment by indatawetrust** [comment]
@lohfu In order to protect your mental health, you should choose alternatives instead of sindre sorhus packages. eg axios :)

**Comment by sindresorhus** [comment]
See https://github.com/sindresorhus/ky/pull/11

@sholladay Maybe we should include a reasoning for why it is like this in the `prefixUrl` docs?

**Comment by sholladay** [comment]
Yeah, we should document it. 👍 

The discussion about it is pretty long but the important bits start around https://github.com/sindresorhus/ky/pull/11#issuecomment-422642912. I would summarize it like this:

1. We want `ky(input, { prefixUrl })` to be unambiguous in its semantics. Specifically, it does _not_ follow the URL resolution algorithm. By restricting the allowed input, we're able to hopefully make this a little more clear and predictable.
2. We want to enforce consistency. Having `myApi('foo')` in one place and `myApi('/foo')` in another place is confusing. Having a One True Way™ is nice in this case.
3. The code to support any combination of optional slashes on `input` and `prefixUrl` would be more fussy and complicated. It sounds trivial, but there are notable edge cases that need to be handled specially due to how `fetch()` will resolve relative URLs. You can see evidence of this in some of the intermediate commits in #11 before we had finalized the algorithm. It's technically doable, but the complexity barely seems worth it to me.
